# Generated by Django 5.2 on 2025-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relayhub', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
    ]
