# Generated by Django 5.2 on 2025-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relayhub', '0005_remove_ticket_response_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
