# Generated by Django 5.2 on 2025-05-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relayhub', '0006_ticket_response_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='response_note',
        ),
    ]
